In [3]:
from SupervisedLearning.LogisticRegression import LogisticRegression

In [4]:

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


In [5]:

# load the breast cancer dataset
X, y = load_breast_cancer(return_X_y=True)

# split the train and test dataset
X_train, X_test,\
    y_train, y_test = train_test_split(X, y,
                                       test_size=0.20,
                                       random_state=23)


In [ ]:

# LogisticRegression
clf = LogisticRegression(0.1,1000)
clf.fit(X_train, y_train)

In [ ]:
# Prediction
y_pred,probabilty = clf.predict(X_test)

In [ ]:
print(y_test)

[1 1 0 1 0 0 0 1 1 0 0 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 1 0 0 1 1 1 1
 1 1 1 1 1 1 0 0 1 1 1 1 1 0 1 0 1 0 0 1 0 1 1 1 0 0 1 1 1 1 1 1 0 0 0 1 1
 1 1 0 1 1 1 1 0 1 1 1 0 1 0 1 0 0 0 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 1 0 1
 1 1 0]


In [ ]:
print(y_pred)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
y_test.size

114

In [ ]:
y_pred.size

114

In [ ]:
print(probabilty)

[[1. 0. 1. ... 0. 1. 0.]
 [1. 0. 1. ... 0. 1. 0.]
 [1. 0. 1. ... 0. 1. 0.]
 ...
 [1. 0. 1. ... 0. 1. 0.]
 [1. 0. 1. ... 0. 1. 0.]
 [1. 0. 1. ... 0. 1. 0.]]


In [ ]:
probabilty.shape

(114, 455)

In [ ]:
clf.W.shape

(30, 455)

In [ ]:
clf.threshold

0.5

In [ ]:
clf.__dict__

NameError: name 'clf' is not defined

In [ ]:
clf.forward_propogation()

NameError: name 'clf' is not defined

In [8]:
import numpy as np

In [14]:
W=y_test.T
B=2

In [15]:
X_test.shape

(114, 30)

In [19]:
W.shape

(114,)

In [22]:
def forward_propogation(X_test):
    z=np.multiply(W,X_test)+B
    probabilty=1/(1+np.exp(-z))
    return probabilty

In [23]:
forward_propogation(X_test)

ValueError: operands could not be broadcast together with shapes (114,) (114,30) 